### ISSUE TITLE
support for ruby 1.8.7 / puppet 2.7

### ISSUE THREAD

**Issue by liamjbennett** [puppetlabs/puppetlabs-reboot#12]
I'm using puppet 2.7.19 which uses ruby 1.8.7

The reboot module fails with the following error:

```
undefined method 'pipeline_w' for Open3:Module
```

This method was not introduced until 1.9.x

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
