### ISSUE TITLE
Pending reboot due to "Windows Device Installation" not detected

### ISSUE THREAD

**Issue by ringods** [puppetlabs/puppetlabs-reboot#17]
I have a Vagrant template of a Windows 2008R2 that was once created on VirtualBox running on a Core 2 Duo. This template is now used on machines running a Core i7. When the machine starts, Windows detects the newer CPU and "Windows Device Installation" kicks in to install the driver(?) for the Intel Core i7, leading to a pending restart.

This pending reboot is not detected by the reboot provider. If I would know where to look in the system (registry?) to detect this, I could provide a pull request, but for the time being I hope the community can help out.

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
