### ISSUE TITLE
Usage of module with "when => pending"

### ISSUE THREAD

**Issue by stack72** [puppetlabs/puppetlabs-reboot#18]
Hey @joshcooper (and @ferventcoder)

I am trying to use the module in the following way:

```
class profiles::windows::reboot {

  reboot { 'Windows Reboot':
     when => pending,
  }
}
```

This is pretty much added at the end of a role as follows:

```
class roles::search_api {
  include profiles::windows::base
  include profiles::windows::dotnet40
  include profiles::windows::webserver
  include profiles::windows::iotsys

  include profiles::configuration::search_api
  include profiles::windows::reboot

  Class['profiles::windows::base'] -> Class['profiles::windows::dotnet40'] ->  Class['profiles::windows::webserver'] -> Class['profiles::windows::iotsys'] -> Class['profiles::configuration::search_api'] -> Class['profiles::windows::reboot']
}
```

I cannot require this after a specific class due to the use of profiles and reusability but I can implement it and say that it will happen when pending. The trouble is that I never seem to trigger the module even though my system prompts me to tell me to reboot

Is then when pending even a valid use case here?

Paul

**Comment by chelnak** [comment]
Hello! We are doing some house keeping and noticed that this issue has been open for a long time.

We're going to close it but please do raise another issue if the issue still persists. 😄
